name: Build and test package
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  push:
    branches:
      - main
      - master
      - develop
      - 'release/**'
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Upload Artifact
    steps:
    - uses: actions/checkout@v3

    - name: yarn install and build
      run: |
         yarn install --frozen-lockfile
         yarn build

    - uses: actions/upload-artifact@main
      with:
        name: artifact-built-by-yarn
        path: dist/

  test:
    needs: build
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@main
      with:
        name: artifact-built-by-yarn
        path: dist/

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install, and test
      run: |
        yarn install
        yarn test
      env:
        CI: true
